# Generated by Django 6.0.1 on 2026-01-13 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_onetimelogintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
