# Generated by Django 6.0.1 on 2026-01-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
