# Generated by Django 6.0.1 on 2026-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('total_candidates', models.IntegerField(default=0)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_calculated', models.BooleanField(default=False)),
            ],
        ),
    ]
