# Generated by Django 6.0.1 on 2026-01-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='total_candidates',
        ),
    ]
