# Generated by Django 6.0.1 on 2026-01-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_settings_total_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
