# Generated by Django 6.0.1 on 2026-01-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_expense_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_requested',
        ),
    ]
